########################################################
# profile配置
#profile:
#  active: dev

########################################################
# 应用配置
app:
  name: dartboot_example # 应用名可以自定义修改

########################################################
# 服务配置
server:
  port: 8080 # 端口可以自定义修改
  context-path: /example/api # 上下文可以自定义修改

database:
  mysql:
    dev:
      host: 192.168.1.xx
      port: 3306
      db: xx
      username: xx
      password: xx
      max-pool-size: 2